### ISSUE TITLE
Implicit dependency on `::ActionDispatch::Static` breaks Rails environment

### ISSUE THREAD

**Issue by grekko** [github/view_component#1112]
## Summary

ViewComponent recently added support to view the source code of a preview (see https://github.com/github/view_component/pull/667).

For this ViewComponent bundles `prism` which is served via a `ActionDispatch::Static`-middleware, inserted here https://github.com/github/view_component/blob/928f86c6c6ce048d791f2f5874f662780b3bed7e/lib/view_component/engine.rb#L106

The call to [`app.middleware.insert_before`](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_dispatch/middleware/stack.rb#L100-L103) will fail though, if there is no `ActionDispatch::Static` class already defined in the Rails middleware stack.

E.g. our Rails staging environment has configured `config.public_file_server.enabled = false`, which tells Rails to [not add](https://github.com/rails/rails/blob/90357af08048ef5076730505f6e7b14a81f33d0c/railties/lib/rails/application/default_middleware_stack.rb#L25-L29) `ActionDispatch::Static` to the default middleware stack.

Trying to render the middleware stack will cause an error:

```sh
RAILS_ENV=staging bundle exec rails middleware
No such middleware to insert before: ActionDispatch::Static
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:108:in `assert_index'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/stack.rb:75:in `insert'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/configuration.rb:71:in `block in merge_into'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/configuration.rb:70:in `each'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/configuration.rb:70:in `merge_into'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:509:in `block in app'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:506:in `synchronize'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:506:in `app'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
/var/www/path-to-app/releases/20211029122602/config/environment.rb:5:in `<main>'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:337:in `require_environment!'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/command.rb:48:in `invoke'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/commands.rb:18:in `<main>'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/var/www/path-to-app/shared/bundle/ruby/2.7.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => middleware => environment
(See full trace by running task with --trace)
```

Changing `config.public_file_server.enabled` from `false` to `true` will resolve the issue.

```diff
diff --git a/config/environments/staging.rb b/config/environments/staging.rb
index 4d37fda61..041560761 100644
--- a/config/environments/staging.rb
+++ b/config/environments/staging.rb
@@ -24,7 +24,7 @@ Application.configure do
 
   # Disable serving static files from the `/public` folder by default since
   # Apache or NGINX already handles this.
-  config.public_file_server.enabled = false
+  config.public_file_server.enabled = true
 
   # Compress JavaScripts and CSS.
   config.assets.js_compressor = Uglifier.new(harmony: true)
```

Now the middleware stack is rendered and contains 2 instances of `ActionDispatch::Static` – 1 added by Rails, and 1 by the ViewComponent engine.

```sh
RAILS_ENV=staging bundle exec rails middleware
use CustomMiddleware::Utf8Sanitizer
use CustomMiddleware::HandleRackInvalidEncoding
use Rack::MiniProfiler
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Static
use ActionDispatch::Executor
use Sentry::Rails::CaptureExceptions
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use Remotipart::Middleware
use Sentry::Rails::RescuedExceptionInterceptor
use Rack::Auth::Basic
use OmniAuth::Builder
use ActionDispatch::Static
use Rack::Pjax
run Application.routes
```

## Proposed Solutions

Could we not just append the middleware via [`app.middleware.use`](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_dispatch/middleware/stack.rb#L143-L145), which would append the `ActionDispatch::Static`-middleware without a reference?

In my application this would add `ActionDispatch::Static` just before `Application.routes`, which did not cause any issues (for me).

**Comment by joelhawksley** [comment]
@grekko thank you for the report! @johannesengl do you have any preference for how we resolve this?

If I had to pick, I'd vote that we ship a fix to unblock folks that checks to see if `config.public_file_server.enabled` is `true` to enable previews. We should then document this requirement. 

From there we can look at other approaches. @grekko perhaps you could write a PR that does ☝🏻

**Comment by grekko** [comment]
Hi @joelhawksley

> If I had to pick, I'd vote that we ship a fix to unblock folks that checks to see if config.public_file_server.enabled is true to enable previews.

From what I understand, users do not need to enable `config.public_file_server.enabled` for the source code preview to work.

🤔 could you elaborate why you would not change the call from [`ActionDispatch::MiddlewareStack#insert_before`](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_dispatch/middleware/stack.rb#L100-L103) to [`ActionDispatch::MiddlewareStack#use`](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_dispatch/middleware/stack.rb#L143-L145)?

See #1116

**Comment by joelhawksley** [comment]
@grekko can we close this issue given #1116 has been merged?
