### ISSUE TITLE
`bundle exec appraisal rake` fails with "`initialize': wrong number of arguments"

### ISSUE THREAD

**Issue by sampart** [github/view_component#1326]
I’m trying to run the the tests from this project locally. I’m running through the setup steps at https://github.com/github/view_component/blob/main/docs/CONTRIBUTING.md#submitting-a-pull-request. I had to run `bundle install` before `bundle exec appraisal install` but anyway.

The issue I’m hitting is with `bundle exec appraisal rake`:

```
$ bundle exec appraisal rake          
>> BUNDLE_GEMFILE=/Users/sam/code/other/view_component/gemfiles/rails_5.2.gemfile bundle exec rake
/Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-5.2.7/lib/active_support/core_ext/hash/except.rb:12: warning: method redefined; discarding old except
/Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/static.rb:111:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
```

<details>
<summary>Fuller stack trace</summary>

```
$ bundle exec appraisal rake          
>> BUNDLE_GEMFILE=/Users/sam/code/other/view_component/gemfiles/rails_5.2.gemfile bundle exec rake
/Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-5.2.7/lib/active_support/core_ext/hash/except.rb:12: warning: method redefined; discarding old except
/Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/static.rb:111:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/stack.rb:37:in `new'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/stack.rb:37:in `build'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/stack.rb:101:in `each'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/stack.rb:101:in `inject'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-5.2.7/lib/action_dispatch/middleware/stack.rb:101:in `build'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/engine.rb:510:in `block in app'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/engine.rb:506:in `synchronize'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/engine.rb:506:in `app'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/initializable.rb:32:in `run'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/application.rb:361:in `initialize!'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/railtie.rb:190:in `public_send'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-5.2.7/lib/rails/railtie.rb:190:in `method_missing'
	from /Users/sam/code/other/view_component/test/sandbox/config/environment.rb:7:in `<top (required)>'
	from /Users/sam/code/other/view_component/test/test_helper.rb:25:in `require'
	from /Users/sam/code/other/view_component/test/test_helper.rb:25:in `<top (required)>'
	from /Users/sam/code/other/view_component/test/generators/component_generator_test.rb:3:in `require'
	from /Users/sam/code/other/view_component/test/generators/component_generator_test.rb:3:in `<top (required)>'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /Users/sam/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/Users/sam/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/Users/sam/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

</details>

I’m using rbenv for my ruby versioning and have tried with both Ruby 3.0.1 and 3.0.3. I've also tried this in a Codespace.

@spone, `@joelhawksley` suggested I tag you as you [added Appraisal](https://github.com/github/view_component/pull/1225). Any ideas? Thanks in advance.

**Comment by camertron** [comment]
Thanks @sampart :) Turns out Rails 5.2 doesn't run so well on Ruby 3. Should be fixed now.
