### ISSUE TITLE
Some capybara assertions (e.g. `assert_button`) failing after 2.58 -> 2.59 upgrade

### ISSUE THREAD

**Issue by tjefferson08** [github/view_component#1425]
### Steps to reproduce
[reproduction in repo here](https://github.com/tjefferson08/view-component-capyabara-assertion-bug)

Basic steps: 
- install view_component 2.59 and capybara (3.37.1 in this case)
- add a test which uses `assert_button`
- observe failure! 
- downgrade to 2.58 and observe success

### Expected behavior
API from capybara like `assert_button` should correctly flow through to the Capybara assertion/matcher API

### Actual behavior
```
12:43 $ bin/rails test -b
Running 1 tests in a single process (parallelization threshold is 50)
Run options: -b --seed 64580

# Running:

E

Error:
ButtonComponentTest#test_button_exists:
ArgumentError: Unused parameters passed to Capybara::Queries::SelectorQuery : [:button, "Hello"]
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/queries/selector_query.rb:52:in `initialize'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/node/matchers.rb:842:in `new'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/node/matchers.rb:842:in `_verify_selector_result'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/node/matchers.rb:110:in `assert_selector'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/view_component-2.59.0/lib/view_component/capybara_simple_session.rb:74:in `assert_selector'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/view_component-2.59.0/lib/view_component/test_helpers.rb:17:in `call'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/view_component-2.59.0/lib/view_component/test_helpers.rb:17:in `assert_selector'
    /Users/travis/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/minitest.rb:288:in `block (2 levels) in <module:Assertions>'
    /Users/travis/view_component-bug-replica/test/components/button_component_test.rb:9:in `test_button_exists'
```

### System configuration
**Rails version**:
7.0.3

**Ruby version**:
3.1.1

**Gem version**:
2.59

**Comment by rmacklin** [comment]
Related:
- https://github.com/github/view_component/pull/1423

**Comment by joelhawksley** [comment]
Reverted in https://github.com/github/view_component/releases/tag/v2.61.1.
