### ISSUE TITLE
`pvc` run failing on `main` after #1462 merged

### ISSUE THREAD

**Issue by boardfish** [github/view_component#1467]
CI runs are failing with the following message under `pvc`:

```
/home/runner/work/view_component/view_component/primer_view_components/test/primer/forms/forms_test.rb:8:in `<class:FormsTest>': uninitialized constant ViewComponent::RenderPreviewHelper (NameError)
[632](https://github.com/github/view_component/runs/7777028692?check_suite_focus=true#step:7:633)
	from /home/runner/work/view_component/view_component/primer_view_components/test/primer/forms/forms_test.rb:6:in `<main>'
[633](https://github.com/github/view_component/runs/7777028692?check_suite_focus=true#step:7:634)
```

Looks like this was introduced by #1462.

**Comment by joelhawksley** [comment]
Yup, we need to bump VC in PVC. I'll take this one ❤️
