### ISSUE TITLE
Help: bug when upgrade to latest version

### ISSUE THREAD

**Issue by nquocvuong** [github/view_component#257]
Hi guys,

after upgrade actionview-component from 1.5.3 to 1.15.0.

I start rails server and got this error

![image](https://user-images.githubusercontent.com/33539765/76405165-4fac9a00-63ba-11ea-9cde-4835a91dfab6.png)

I dig into your codebase.  and I found that the following snippet code cause this error

```ruby
   #lib/view_component/engine.rb
    ActiveSupport.on_load(:action_controller) do
        ActionController::Base.prepend ViewComponent::RenderingMonkeyPatch
      end
```
any suggestion for me?

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.5

**Gem version**: 1.5.0

**Comment by joelhawksley** [comment]
@nquocvuong thanks for the report!

Jumping from `1.5.0` to `1.15.0` is a big leap. Would you be willing to step through the releases to see which one introduced this error in your codebase?

**Comment by nquocvuong** [comment]
Hi @joelhawksley 

thank for the response. it occur on version 1.13.0 with the appearance of Component::RenderingMonkeyPatch

**Comment by joelhawksley** [comment]
@nquocvuong interesting, it looks like something is frozen that isn't frozen in other environments.

Can you inspect the state of `ActionController::Base` before that line to see if perhaps it's trying to prepend multiple times?

**Comment by nquocvuong** [comment]
> Can you inspect the state of ActionController::Base before that line to see if perhaps it's trying to prepend multiple times?

I tried to inspect all ancestors of `ActionController::Base` and look like this code run twice -> prepend twice
![image](https://user-images.githubusercontent.com/33539765/76590798-e98e5700-6520-11ea-93a8-53785f962c6a.png)

but if I write a condition to make it prepend one time, this bug still occurs.

note: it raises an error whenever `ActionController::Base` call render( visit a URL of my app) not when starting server, sorry my post was a mistake.

**Comment by joelhawksley** [comment]
@nquocvuong thanks for taking the time to do that diagnostic.

Would you be willing to take on writing a fix?

If not, could you provide an example Rails app repo that reproduces this failure?

**Comment by joelhawksley** [comment]
@nquocvuong can you attempt to reproduce this bug on `v2.0.0`, and if so, provide an example Rails app that reproduces the failure?

**Comment by nquocvuong** [comment]
ok, I will give a try on `v2.0.0`

**Comment by spdawson** [comment]
I hit what may be the same problem using `view_component` in a fairly complex Rails application. In my case, I was eventually able to track the issue down to an incompatibility between `view_component` and [`wicked_pdf`](https://github.com/mileszs/wicked_pdf) &mdash; demonstration application [here](https://github.com/spdawson/view_component-frozen-error).

It seems that the technique of monkey patching `ActionController::Base#render` doesn't interact well with other libraries that use the same technique.

**Comment by joelhawksley** [comment]
@spdawson thank you for taking the time to reproduce this bug! 🙇 

@nquocvuong are you using a gem that also monkey patches `ActionController::Base#render`?

What do you think is the right solution here? I have some ideas, but I'd like to hear your thoughts first 😄

**Comment by nquocvuong** [comment]
HI @joelhawksley,
sorry for late.
today I upgrade to `2.1.0` and still get the same error ( error 41 render_monkey_patch)

```
/home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `catch': exception reentered (fatal)
/home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `catch': can't modify frozen fatal (FrozenError)
	83: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
	82: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
	81: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
	80: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
	79: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
	78: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
	77: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
	76: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
	75: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
	74: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
	73: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
	72: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/font_assets-0.1.14/lib/font_assets/middleware.rb:16:in `call'
	71: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/font_assets-0.1.14/lib/font_assets/middleware.rb:40:in `do_request'
	70: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/font_assets-0.1.14/lib/font_assets/middleware.rb:17:in `block in call'
	69: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
	68: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/deflater.rb:44:in `call'
	67: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
	66: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	65: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
	64: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
	63: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
	62: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
	61: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	60: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	59: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
	58: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
	57: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
	56: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
	55: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
	54: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
	53: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	52: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `call'
	51: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `catch'
	50: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:28:in `block in call'
	49: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:132:in `call_app'
	48: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:30:in `call'
	47: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:43:in `rescue in call'
	46: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:74:in `render_exception'
	45: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:89:in `render_for_browser_request'
	44: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_view.rb:50:in `render'
	43: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/logger_silence.rb:36:in `silence'
	42: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_view.rb:50:in `block in render'
	41: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/view_component-2.1.0/lib/view_component/render_monkey_patch.rb:9:in `render'
	40: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/helpers/rendering_helper.rb:30:in `render'
	39: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/base.rb:304:in `in_rendering_context'
	38: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
	37: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:22:in `render'
	36: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
	35: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
	34: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:13:in `render'
	33: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:57:in `render_template'
	32: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
	31: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:58:in `block in render_template'
	30: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
	29: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:182:in `instrument'
	28: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
	27: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:59:in `block (2 levels) in render_template'
	26: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:183:in `render'
	25: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:386:in `instrument_render_template'
	24: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:182:in `instrument'
	23: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:185:in `block in render'
	22: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/base.rb:274:in `_run'
	21: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb:37:in `__home_vuong__rbenv_versions_______lib_ruby_gems_______gems_actionpack_________lib_action_dispatch_middleware_templates_rescues_diagnostics_html_erb___1314815733186861500_47419797341140'
	20: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_view.rb:50:in `render'
	19: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/logger_silence.rb:36:in `silence'
	18: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_view.rb:50:in `block in render'
	17: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/view_component-2.1.0/lib/view_component/render_monkey_patch.rb:9:in `render'
	16: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/helpers/rendering_helper.rb:30:in `render'
	15: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/base.rb:304:in `in_rendering_context'
	14: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
	13: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:22:in `render'
	12: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
	11: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
	10: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:13:in `render'
	 9: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:57:in `render_template'
	 8: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
	 7: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:58:in `block in render_template'
	 6: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
	 5: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:182:in `instrument'
	 4: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
	 3: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:59:in `block (2 levels) in render_template'
	 2: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:182:in `render'
	 1: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:188:in `rescue in render'
/home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.1/lib/action_view/template.rb:355:in `handle_render_error': can't modify frozen fatal (ActionView::Template::Error)
	36: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
	35: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
	34: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
	33: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
	32: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
	31: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
	30: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
	29: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/webpacker-4.2.2/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
	28: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
	27: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
	26: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
	25: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/font_assets-0.1.14/lib/font_assets/middleware.rb:16:in `call'
	24: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/font_assets-0.1.14/lib/font_assets/middleware.rb:40:in `do_request'
	23: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/font_assets-0.1.14/lib/font_assets/middleware.rb:17:in `block in call'
	22: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
	21: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/deflater.rb:44:in `call'
	20: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
	19: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	18: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
	17: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
	16: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
	15: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
	14: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	13: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	12: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
	11: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
	10: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
	 9: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
	 8: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
	 7: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
	 6: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	 5: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `call'
	 4: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `catch'
	 3: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:28:in `block in call'
	 2: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:131:in `call_app'
	 1: from /home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:134:in `rescue in call_app'
/home/vuong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:134:in `throw': uncaught throw :app_exception (UncaughtThrowError)

```
> @nquocvuong are you using a gem that also monkey patches ActionController::Base#render?

I'm not sure, let me check it out. I'm investigating the solution

**Comment by koenhandekyn** [comment]
@joelhawksley for your info, I'm working on the same project as @nquocvuong and I can confirm we also have wicked_pdf in that project
