### ISSUE TITLE
Component raises an exception in tests when its template renders a partial

### ISSUE THREAD

**Issue by BlakeWilliams** [github/view_component#500]
### Steps to reproduce
Create a component that has a template that uses `render` to render a partial. e.g.

```
<%= render "my_partial" %>
```

Use `render_inline(MyComponent.new)` to render the component

### Expected behavior
The component renders with the partial.

### Actual behavior
An Exception is raised

```
NoMethodError: undefined method `_app_views_my_partial_html_erb___1622271391424259503_260600' for #<MyComponent:0x0000000123c911b0>
```

It looks like compiling the template turns the `render "my_partial"` call into the above method, but it's not defined on the component or the `view_context.compiled_method_container`.

### System configuration
**Rails version**:
6.1

**Ruby version**:
2.7.1

**Gem version**:
2.9.1

**Comment by BlakeWilliams** [comment]
Looks like the cause wasn't view components themselves, closing for now.

**Comment by dkniffin** [comment]
@BlakeWilliams I'm seeing something similar in my app. Can you share what the cause of it was in your case?

**Comment by caifara** [comment]
@dkniffin I bumped into this, but ultimately came up with this: https://github.com/github/view_component/pull/538

**Comment by niladrix719** [comment]
@BlakeWilliams hi i was rendering a view component in test but 'render_inline' method seems to be undefined.

```
TableRow::TableRowComponent
  renders the assignment row correctly (FAILED - 1)

Failures:

  1) TableRow::TableRowComponent renders the assignment row correctly
     Failure/Error:
       render_inline(described_class.new(
                       @assignment,
                       @current_user,
                       @group,
                       { minute: 30, day: 15, year: 2023, second: 0, hour: 12, month: 10 }
                     ))
     
     NoMethodError:
       undefined method `render_inline' for #<RSpec::ExampleGroups::TableRowTableRowComponent "renders the assignment row correctly" (./spec/components/table_row_component_spec.rb:13)>
     # ./spec/components/table_row_component_spec.rb:14:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 0.08942 seconds (files took 6.15 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/components/table_row_component_spec.rb:13 # TableRow::TableRowComponent renders the assignment row correctly

Lcov style coverage report generated for RSpec to /workspaces/CircuitVerse/coverage/lcov/CircuitVerse.lcov
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

i have this right now: 

```
# frozen_string_literal: true

require "rails_helper"

RSpec.describe TableRow::TableRowComponent, type: :component do
  before do
    @primary_mentor = FactoryBot.create(:user)
    @group = FactoryBot.create(:group, primary_mentor: @primary_mentor)
    @assignment = FactoryBot.create(:assignment, group: @group)
    @current_user = FactoryBot.create(:user)
  end

  it "renders the assignment row correctly" do
    render_inline(described_class.new(
                    @assignment,
                    @current_user,
                    @group,
                    { minute: 30, day: 15, year: 2023, second: 0, hour: 12, month: 10 }
                  ))
  end
end
```

**Comment by BlakeWilliams** [comment]
@niladrix719 Is that related to this issue?

**Comment by niladrix719** [comment]
> @niladrix719 Is that related to this issue?

probably

**Comment by garlou** [comment]
I had to include this on the spec_helper.rb to make it work
```
require 'view_component/test_helpers'
require 'view_component/system_test_helpers'
require 'capybara/rspec'
...
RSpec.configure do |config|
  config.include ViewComponent::TestHelpers, type: :component
  config.include ViewComponent::SystemTestHelpers, type: :component
  config.include Capybara::RSpecMatchers, type: :component
...
```

**Comment by reeganviljoen** [comment]
@BlakeWilliams I see a lot of necro posting here, do you think we should re-open this one
